sudo: false
language: python
matrix:
  include:

  - os: linux
    python: "3.5"
    env: MODE="normal" REQS="dev-requirements.txt"

  - os: linux
    env: NAME=pytest2
    python: "2.7"
    install:
      - pip install -r python2.7-dev-requirements.txt
      - dev_tools/pip-install-cirq-python2-from-head.sh
    script: check/pytest2

branches:
  only:
    - master

before_install:
  - pip install --upgrade pip setuptools wheel

install:
  - pip install -r ${REQS}

script: continuous-integration/travis.sh "${MODE}"
