sudo: false
language: python

branches:
  only:
    - master

before_install:
  - pip install --upgrade pip setuptools wheel

matrix:
  include:
  - os: linux
    env: NAME=mypy
    python: "3.5.2"
    install:
      - cat dev_tools/conf/pip-list-dev-tools.txt | grep mypy | xargs pip install
    script: check/mypy

  - os: linux
    env: NAME=pylint
    python: "3.5.2"
    install:
      - cat dev_tools/conf/pip-list-dev-tools.txt | grep pylint | xargs pip install
    script: check/pylint

  - os: linux
    env: NAME=pytest-and-incremental-coverage
    python: "3.5.2"
    install:
      - pip install -r requirements.txt
      - pip install -r dev_tools/conf/pip-list-dev-tools.txt
    script: check/pytest-and-incremental-coverage master

  - os: linux
    env: NAME=pytest
    python: "3.6"
    install:
      - pip install -r requirements.txt
      - pip install -r dev_tools/conf/pip-list-dev-tools.txt
    script: check/pytest

  - os: linux
    env: NAME=pytest2
    python: "2.7"
    install:
      - pip install -r dev_tools/python2.7-requirements.txt
      - pip install -r dev_tools/conf/pip-list-python2.7-test-tools.txt
    script: check/pytest2
